package alg

case class GPSEvent(
                     timestamp: Double,
                     lat: Double,
                     lon: Double,
                     alt: Double,
                     roll: Double,
                     pitch: Double,
                     yaw: Double,
                     vn: Double,
                     ve: Double,
                     vf: Double,
                     vl: Double,
                     vu: Double,
                     ax: Double,
                     ay: Double,
                     az: Double,
                     af: Double,
                     al: Double,
                     au: Double,
                     wx: Double,
                     wy: Double,
                     wz: Double,
                     wf: Double,
                     wl: Double,
                     wu: Double,
                     pos_accuracy: Double,
                     vel_accuracy: Double,
                     navstat: Int,
                     numsats: Int,
                     posmode: Int,
                     velmode: Int,
                     orimode: Int
                   )
